---
- name: Debug worker
  debug:
    var: worker

- name: Set worker name as fact
  set_fact:
    worker_name: "{{ worker.tags.Name }}"

- name: CSR configuration for "{{ worker_name }}"
  template:
    src: "{{ role_path }}/templates/kubelet-csr.json.j2"
    dest: "{{ certificates_dir }}/kubelet-{{ worker_name }}-csr.json"

- name: Generate certificate & key for "{{ worker_name }}"
  shell: |
    cfssl gencert \
     -ca=ca.pem \
     -ca-key=ca-key.pem \
     -config=ca-config.json \
     -hostname={{ worker.private_dns_name }},{{ worker.private_ip_address }},{{ worker.public_ip_address }} \
     -profile=kubernetes \
     kubelet-{{ worker_name }}-csr.json | cfssljson -bare kubelet-{{ worker_name }}
  args:
    chdir: "{{ certificates_dir }}"
    creates: "kubelet-{{ worker_name }}.pem"
