---
- name: Download Kubernetes worker binaries
  shell: |
    wget -q --show-progress --https-only --timestamping \
    https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.15.0/crictl-v1.15.0-linux-amd64.tar.gz \
    https://github.com/opencontainers/runc/releases/download/v1.0.0-rc8/runc.amd64 \
    https://github.com/containernetworking/plugins/releases/download/v0.8.2/cni-plugins-linux-amd64-v0.8.2.tgz \
    https://github.com/containerd/containerd/releases/download/v1.2.9/containerd-1.2.9.linux-amd64.tar.gz \
    https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kubectl \
    https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kube-proxy \
    https://storage.googleapis.com/kubernetes-release/release/v1.15.3/bin/linux/amd64/kubelet

- name: Set directories
  become: true
  shell: |
    mkdir -p \
    /etc/cni/net.d \
    /opt/cni/bin \
    /var/lib/kubelet \
    /var/lib/kube-proxy \
    /var/lib/kubernetes \
    /var/run/kubernetes

- name: Install binaries
  become: true
  shell: |
    mkdir containerd
    tar -xvf crictl-v1.15.0-linux-amd64.tar.gz
    tar -xvf containerd-1.2.9.linux-amd64.tar.gz -C containerd
    tar -xvf cni-plugins-linux-amd64-v0.8.2.tgz -C /opt/cni/bin/
    mv runc.amd64 runc
    chmod +x crictl kubectl kube-proxy kubelet runc 
    mv crictl kubectl kube-proxy kubelet runc /usr/local/bin/
    mv containerd/bin/* /bin/
