---
- name: Set cluster for "{{ service }}"
  shell: |
    kubectl config set-cluster kubernetes-the-hard-way \
    --certificate-authority=ca.pem \
    --embed-certs=true \
    --server=https://{{ kube_apiserver_endpoint }}:6443 \
    --kubeconfig={{ service }}.kubeconfig
  args:
    chdir: "{{ cka_dir }}"

- name: Set credentials for "{{ service }}"
  shell: |
    kubectl config set-credentials system:node:{{ service }} \
    --client-certificate={{ service }}.pem \
    --client-key={{ service }}-key.pem \
    --embed-certs=true \
    --kubeconfig={{ service }}.kubeconfig
  args:
    chdir: "{{ cka_dir }}"

- name: Set context for "{{ service }}"
  shell: |
    kubectl config set-context default \
    --cluster=kubernetes-the-hard-way \
    --user="{{ kube_user }}" \
    --kubeconfig={{ service }}.kubeconfig
  args:
    chdir: "{{ cka_dir }}"

- name: Use context for "{{ service }}"
  shell: |
    kubectl config use-context default \
    --kubeconfig={{ service }}.kubeconfig
  args:
    chdir: "{{ cka_dir }}"
