---
- name: Run the equivalent of "apt-get update" as a separate step
  become: true
  apt:
    update_cache: yes

- name: Install system packages
  become: true
  loop: "{{ packages }}"
  package:
    name: "{{ item }}"
    state: present

- name: Install pip
  become: true
  block:
    - name: Fetch Pip
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: "/tmp/get-pip.py"

    - name: Install Pip
      shell: python3 /tmp/get-pip.py

- name: Install Python packages
  loop: "{{ python_packages }}"
  pip:
    executable: "pip3"
    name: "{{ item }}"

- name: Set an Ansible directory
  file:
    path: "{{ ansible_directory }}"
    state: "directory"
    mode: "0700"

- name: Copy node configuration
  copy:
    src: "{{ cka_dir }}"
    dest: "{{ ansible_directory }}"
