---
- name: Make K8S configuration dir
  become: true
  file:
    path: "{{ k8s_conf_dir }}"
    state: directory

- name: Copy configuration
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ k8s_conf_dir }}"
    remote_src: true
  loop:
    - "{{ cka_dir }}/ca.pem"
    - "{{ cka_dir }}/ca-key.pem"
    - "{{ cka_dir }}/kubernetes.pem"
    - "{{ cka_dir }}/kubernetes-key.pem"
    - "{{ cka_dir }}/service-account.pem"
    - "{{ cka_dir }}/service-account-key.pem"
    - "{{ cka_dir }}/encryption-config.yaml"
    - "{{ cka_dir }}/kube-controller-manager.kubeconfig"
    - "{{ cka_dir }}/kube-scheduler.kubeconfig"
    - "{{ cka_dir }}/admin.kubeconfig"

- name: Set Kubernetes controller services
  become: true
  loop:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  vars:
    apiserver_endpoint: "{{ hostvars.localhost.public_eip.addresses.0.public_ip }}"

- name: Make Kubernetes config directory
  become: true
  file:
    path: "{{ kube_config_path }}"
    state: "directory"

- name: Set Kubernetes scheduler configuration
  become: true
  template:
    src: "kube-scheduler.yml.j2"
    dest: "{{ kube_config_path }}/kube-scheduler.yml"

- name: Set Nginx configuration
  become: true
  block:
    - name: Set virtual server
      template:
        src: "kubernetes.default.svc.cluster.local.j2"
        dest: "{{ nginx_config_path }}/sites-available/kubernetes.default.svc.cluster.local"

    - name: Link virtual server
      file:
        src: "{{ nginx_config_path }}/sites-available/kubernetes.default.svc.cluster.local"
        dest: "{{ nginx_config_path }}/sites-enabled/kubernetes.default.svc.cluster.local"
        state: link
