---
- name: Make K8S configuration dir
  become: true
  file:
    path: "{{ k8s_conf_dir }}"
    state: directory

- name: Copy configuration
  become: true
  copy:
    src: "{{ item }}"
    dest: "{{ etcd_conf_dir }}"
    remote_src: true
  loop:
    - "{{ cka_dir }}/ca.pem"
    - "{{ cka_dir }}/ca-key.pem"
    - "{{ cka_dir }}/kubernetes.pem"
    - "{{ cka_dir }}/kubernetes-key.pem"
    - "{{ cka_dir }}/service-account.pem"
    - "{{ cka_dir }}/service-account-key.pem"
    - "{{ cka_dir }}/encryption_config.yml"

- name: Set Kubernetes controller services
  become: true
  loop:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
  vars:
    apiserver_endpoint: "{{ hostvars.localhost.public_eip.addresses.0.public_ip }}"

- name: Make Kubernetes config directory
  become: true
  file:
    path: "{{ kube_config_path }}"
    state: "directory"

- name: Set Kubernetes controller services
  become: true
  template:
    src: "kube-scheduler.yml.j2"
    dest: "{{ kube_config_path }}/kube-scheduler.yml"
