---
- name: Download Kubernetes control plane
  loop:
    - "kube-apiserver"
    - "kube-controller-manager"
    - "kube-scheduler"
    - "kubectl"
  include_tasks: download_k8s.yml
  vars:
    k8s_binary: "{{ item }}"
- include_tasks: configure_k8s.yml
- include_tasks: run_k8s.yml
- include_tasks: rbac_kubelet.yml
