---
- name: Reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: Enable Kubernetes services
  become: true
  loop:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no

- name: Start Kubernetes services
  become: true
  loop:
    - kube-apiserver.service
    - kube-controller-manager.service
    - kube-scheduler.service
  systemd:
    name: "{{ item }}"
    state: restarted
