---
- name: Reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: Enable etcd
  become: true
  systemd:
    name: etcd
    enabled: yes
    masked: no

- name: Start etcd
  become: true
  systemd:
    name: etcd
    state: restarted
