---
- hosts: "localhost"
  name: Initialize CA
  gather_facts: false

  vars:
    cka_dir: "/tmp/cka"

  tasks:
    - include_role:
        name: create_certificates
      tags: certificates

    - include_role:
        name: create_kubeconfigs
      tags: kubeconfigs
