---
- hosts: "master"
  name: Install master nodes
  gather_facts: true

  tasks:
    - import_role:
        name: init_node
      tags: init

    - import_role:
        name: etcd
      tags: etcd

    - import_role:
        name: kubernetes_control_plane
      tags: kubernetes
