---
- name: Move Kube-Proxy configuration
  become: true
  copy:
    remote_src: true
    src: "{{ cka_dir }}/kube-proxy.kubeconfig"
    dest: "/var/lib/kube-proxy/kubeconfig"

- name: Set Kube-Proxy configuration
  become: true
  loop:
    - source: "kube-proxy-config.yaml.j2"
      destination: "/var/lib/kube-proxy/kube-proxy-config.yaml"
    - source: "kube-proxy.service.j2"
      destination: "/etc/systemd/system/kube-proxy.service"
  template:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
