---
- name: Configure CNI
  become: true
  loop:
    - source: "cni-bridge.conf.j2"
      destination: "/etc/cni/net.d/10-bridge.conf"
    - source: "cni-loopback.conf.j2"
      destination: "/etc/cni/net.d/99-loopback.conf"
  template:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
