---
- name: Make containerd directory
  become: true
  file:
    path: "/etc/containerd"
    state: "directory"

- name: Set Containerd service configuration
  become: true
  loop:
    - source: "containerd.toml.j2"
      destination: "/etc/containerd/config.toml"
    - source: "containerd.service.j2"
      destination: "/etc/systemd/system/containerd.service"
  template:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
