---
- name: Reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: Enable Kubernetes worker services
  become: true
  loop:
    - containerd.service
    - kubelet.service
    - kube-proxy.service
  systemd:
    name: "{{ item }}"
    enabled: yes
    masked: no

- name: Start Kubernetes worker services
  become: true
  loop:
    - containerd.service
    - kubelet.service
    - kube-proxy.service
  systemd:
    name: "{{ item }}"
    state: restarted
